# Generated by Django 6.0.2 on 2026-03-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='risk_level',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
